### ISSUE TITLE
Some missing points, maybe? 

### ISSUE THREAD

**Issue by VahidR** [teivah/sre-roadmap#1]
Hi Teiva, 

Very interesting roadmap. Thanks for sharing your insights. 
A question, though. What about CI/CD, Clouds, and Software Life Cycle Management, etc. in general?

**Comment by teivah** [comment]
Please describe the "etc" part.

**Comment by VahidR** [comment]
Well.. a concept like the PDCA Cycle came to my mind TBH, but it's not that important.

**Comment by VahidR** [comment]
Again, thank you very very much for sharing your insights. I was looking for such knowledge and you kindly provided it in very fine detail. 
I will close this issue...

Cheers,
